# config_cpu.yaml
workerPoolSpecs:
    machineSpec:
        machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
        imageUri: europe-west4-docker.pkg.dev/handy-parity-484212-t1/my-container-registry/main:latest
        env:
        - name: WANDB_API_KEY
          value: $WANDB_API_KEY
