_wandb:
    value:
        cli_version: 0.23.1
        e:
            frektfd0l1hfy670micopxuy0r1gdjoz:
                codePath: ..\..\..\..\..\..\..\Users\gusta\OneDrive - Danmarks Tekniske Universitet\Semester7\MLOPS\dtu_mlops\s4_debugging_and_logging\my_package\src\package\train.py
                codePathLocal: src\package\train.py
                cpu_count: 10
                cpu_count_logical: 12
                disk:
                    /:
                        total: "509722226688"
                        used: "447621255168"
                email: s224031@dtu.dk
                executable: C:\Users\gusta\miniforge3\envs\02452\python.exe
                git:
                    commit: 897e134b7c4667663ac8bffdfee03425038bbd9c
                    remote: https://github.com/SkafteNicki/dtu_mlops
                host: GustavLaptop
                memory:
                    total: "8274370560"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\gusta\OneDrive - Danmarks Tekniske Universitet\Semester7\MLOPS\dtu_mlops\s4_debugging_and_logging\my_package\src\package\train.py
                python: CPython 3.11.13
                root: C:\Users\gusta\OneDrive - Danmarks Tekniske Universitet\Semester7\MLOPS\dtu_mlops\s4_debugging_and_logging\my_package
                startedAt: "2026-01-08T11:32:30.197009Z"
                writerId: frektfd0l1hfy670micopxuy0r1gdjoz
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 16
            "4": 3.11.13
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
batch_size:
    value: 32
epochs:
    value: 5
lr:
    value: 0.001
